# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0f\x63onfuse.auth.v1\"M\n\x17GetInternalTokenRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08provider\x18\x03 \x01(\t\"\x8d\x01\n\x18GetInternalTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x15\n\rrefresh_token\x18\x04 \x01(\t\x12\x12\n\ntoken_type\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"u\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x14\n\x07user_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05roles\x18\x03 \x03(\t\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_user_idB\x08\n\x06_error\"(\n\x15ValidateApiKeyRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"u\n\x16ValidateApiKeyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05roles\x18\x04 \x03(\t\x12\x0e\n\x06key_id\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x9d\x01\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05roles\x18\x03 \x03(\t\x12\x35\n\x08metadata\x18\x04 \x03(\x0b\x32#.confuse.auth.v1.User.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xf5\x02\n\x04\x41uth\x12^\n\rValidateToken\x12%.confuse.auth.v1.ValidateTokenRequest\x1a&.confuse.auth.v1.ValidateTokenResponse\x12\x61\n\x0eValidateApiKey\x12&.confuse.auth.v1.ValidateApiKeyRequest\x1a\'.confuse.auth.v1.ValidateApiKeyResponse\x12g\n\x10GetInternalToken\x12(.confuse.auth.v1.GetInternalTokenRequest\x1a).confuse.auth.v1.GetInternalTokenResponse\x12\x41\n\x07GetUser\x12\x1f.confuse.auth.v1.GetUserRequest\x1a\x15.confuse.auth.v1.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER_METADATAENTRY']._loaded_options = None
  _globals['_USER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_GETINTERNALTOKENREQUEST']._serialized_start=31
  _globals['_GETINTERNALTOKENREQUEST']._serialized_end=108
  _globals['_GETINTERNALTOKENRESPONSE']._serialized_start=111
  _globals['_GETINTERNALTOKENRESPONSE']._serialized_end=252
  _globals['_VALIDATETOKENREQUEST']._serialized_start=254
  _globals['_VALIDATETOKENREQUEST']._serialized_end=291
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=293
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=410
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_start=412
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_end=452
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_start=454
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_end=571
  _globals['_GETUSERREQUEST']._serialized_start=573
  _globals['_GETUSERREQUEST']._serialized_end=606
  _globals['_USER']._serialized_start=609
  _globals['_USER']._serialized_end=766
  _globals['_USER_METADATAENTRY']._serialized_start=719
  _globals['_USER_METADATAENTRY']._serialized_end=766
  _globals['_AUTH']._serialized_start=769
  _globals['_AUTH']._serialized_end=1142
# @@protoc_insertion_point(module_scope)
